version: "3.1"

services:
  app:
    image: golang:1.8
    command: "go run /go/src/app/main.go -d /files -p ${INTERNAL_PORT_WEB}"
    ports:
      - "${EXTERNAL_PORT_WEB}:${INTERNAL_PORT_WEB}"
    volumes:
      - ${FOLDER}:/files
      - ./:/go/src/app
    restart: always
    stdin_open: true
    tty: true
    privileged: true
    network_mode: "bridge"
    privileged: true
